name: robotics3_env
channels:
  - anaconda
  - rpi
  - defaults
dependencies:
  - olefile=0.46
  - pycrypto=2.6.1
  - pyyaml=3.11
  - asn1crypto=0.24.0
  - ca-certificates=2018.8.24
  - certifi=2018.8.24
  - cffi=1.11.5
  - chardet=3.0.4
  - cryptography=2.3.1
  - freetype=2.9.1
  - idna=2.7
  - jpeg=9c
  - libffi=3.2.1
  - libpng=1.6.35
  - libtiff=4.0.9
  - ncurses=6.1
  - openssl=1.0.2r
  - pillow=5.2.0
  - pip=18.0
  - pycosat=0.6.3
  - pycparser=2.18
  - pyopenssl=18.0.0
  - pysocks=1.6.8
  - python=3.6.6
  - readline=7.0
  - requests=2.19.1
  - ruamel_yaml=0.15.63
  - setuptools=40.2.0
  - six=1.11.0
  - sqlite=3.24.0
  - tk=8.6.8
  - urllib3=1.23
  - wheel=0.31.1
  - xz=5.2.4
  - yaml=0.1.7
  - zlib=1.2.11
  - pip:
    - numpy==1.19.4
    - pigpio==1.78
    - readchar==2.0.1
    - tqdm==4.54.0
    - xlrd==2.0.1

